language: go

go:
  - master

before_install:
  - go get -t -v ./...

install:
  - go build -v
  - ./statiq -f -src=./example/public -dest=./example/

script:
  - go test -v -bench=. ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
